name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'extras/images/**'

jobs:
  txt2img:
    name: TXT2IMG Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt

      - name: Run TXT2IMG
        run: python3 run-txt2img.py

      - uses: actions/upload-artifact@v3
        with:
          name: output-txt2img
          path: "*.png"

  img2img:
    name: IMG2IMG Build
    runs-on: ubuntu-latest
    needs: txt2img
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt

      - name: Run IMG2IMG
        run: python3 run-img2img.py

      - uses: actions/upload-artifact@v3
        with:
          name: output-img2img
          path: "*.png"

  upscale:
    name: UPSCALE Build
    runs-on: ubuntu-latest
    needs: img2img
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt

      - name: Run UPSCALE
        run: python3 run-upscale.py

      - uses: actions/upload-artifact@v3
        with:
          name: output-upscale
          path: "*.png"

  cascade:
    name: CASCADE Build
    runs-on: ubuntu-latest
    needs: upscale
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r requirements.txt

      - name: Run CASCADE
        run: python3 run-cascade.py

      - uses: actions/upload-artifact@v3
        with:
          name: output-cascade
          path: "*.png"

  release:
    name: Release Artifacts
    runs-on: ubuntu-latest
    needs: [cascade]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: output/

      - name: Prepare Release Assets
        run: |
          mkdir release-assets
          find output/ -name "*.png" -exec mv {} release-assets/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/*.png
